### ISSUE TITLE
Use versioning of datastore package to enable automated builds of nachet for new versions

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/nachet-backend#109]
## Context 

Currently, the requirements.txt points to the main branch of the package nachet-datastore :
```txt
nachet-datastore @git+https://github.com/ai-cfia/nachet-datastore.git@main
```
There should be versioning on the datastore package that we can use so that our automated bot Renovate can track and propose pull request to update version. This will enable a new deployment package of nachet with dependencies up to date without having to do a build manually. 

## Proposed solution

- Automated tag releases on nachet-datastore
  - [x] [Use a reusable workflow that does the following upon a pull request being **opened**](https://github.com/ai-cfia/github-workflows/issues/141) :
    - checks if the version in pyproject.toml file has been bumped (fails pipeline if not bumped)
  - [x] Use a reusable workflow that does the following upon a pull request being **merged** : 
      - Takes new bumped version from pyprojec.toml to create a new release with changelog
- [x] [Update ailab-datastore folder structure for monorepo management](https://github.com/ai-cfia/ailab-datastore/issues/112)
- [x] #126

Renovate will then be able to automate pull request upon new version releases. That way we can simply merge the pr to have a build and push of a new nachet-backend image with latest changes of nachet-datastore

**Comment by SonOfLope** [comment]
relates to https://github.com/orgs/ai-cfia/projects/7/views/1?pane=issue&itemId=57886391

**Comment by SonOfLope** [comment]
I'm trying to think of the best way to handle this and I think the folder structure would need to be revamped. 

I was thinking of having something like the following : 
```txt
ailab-datastore
├── datastore
│   ├── pyproject.toml
│   ├── requirements.txt
│   ├── __init__.py
│   ├── blob
│   ├── bin
│   ├── tests  # Tests for shared components
│   └── ...
├── nachet
│   ├── pyproject.toml
│   ├── requirements.txt
│   ├── __init__.py
│   ├── tests
│   ├── README.md
│   └── ...
├── fertiscan
│   ├── pyproject.toml
│   ├── requirements.txt
│   ├── __init__.py
│   ├── tests  
│   ├── README.md 
│   └── ...
├── README.md
```

It would be much easier to build separate packages for fertiscan and nachet to which we can point to in respective repositories. Each folder has its own dependencies declaration and tests. 

respective pyprojects file would look like  :
- Nachet: 
```toml
[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nachet-datastore"
version = "0.1.0"
authors = [
  { name = "Francois Werbrouck", email = "francois.werbrouck@inspection.gc.ca" },
  { name = "Sylvanie You", email = "Sylvanie.You@inspection.gc.ca" }
]
description = "Data management python layer for Nachet"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    { path = "../shared" }  
]

license = { file = "../LICENSE" }

keywords = ["Nachet", "ailab"]

[tool.setuptools]
packages = [
    "nachet" 
]

[project.urls]
"Homepage" = "https://github.com/ai-cfia/ailab-datastore/nachet"
"Bug Tracker" = "https://github.com/ai-cfia/ailab-datastore/issues"
"Repository" = "https://github.com/ai-cfia/ailab-datastore"
```

Then versioning could be done automatically through release packages (through a pipeline) with tags like `v0.1.0-nachet-datastore` and `v0.1.0-fertiscan`. We could then use it in nachet (for example) as : 
```txt
nachet-datastore @ git+https://github.com/ai-cfia/ailab-datastore.git@v0.1.0-nachet-datastore
```

This would also enable our Renovate bot to automatically open PR to update  the datastore version in respective repositories. 

@Francois-Werbrouck @k-allagbe   is something like this achievable ? Would it actually help you guys?
